name: Roguetaino
favicon: null
layout_spectrum: 0.49368
typography_spectrum: 1
title: Roguetaino Resistance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c110b'
    - '#8aa4bf'
    - '#b6dbf8'
    - '#373632'
    - '#f4f5f5'
  brandStrength: 0.5625
  lightness: 0.43244253122247756
  saturation: 0.9927992527373135
  rhythmicContrast: 0.515702503034845
purpose: []
