name: Roguetaino
favicon: null
layout_spectrum: 0.21212117723189294
typography_spectrum: 0.06969887716695666
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4476881097070873
  lightness: 0.43244253122247756
  saturation: 0.9927992527373135
  rhythmicContrast: 0.515702503034845
purpose: []
