name: Roguetaino
favicon: null
layout_spectrum: 0.24639
typography_spectrum: 0.09838
title: Roguetaino Resistance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0d14'
    - '#5e7086'
    - '#3a3b3f'
    - '#fffeff'
    - '#a6a29f'
  brandStrength: 0.4476881097070873
  lightness: 0.43244253122247756
  saturation: 0.9927992527373135
  rhythmicContrast: 0.515702503034845
purpose: []
