name: Going Rogue On Aging
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: GROA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8e2eb'
    - '#42505d'
    - '#929c9e'
    - '#1d2528'
    - '#975c25'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
