name: Going Rogue On Aging
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Roguetaino Resistance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c110b'
    - '#8aa4bf'
    - '#b6dbf8'
    - '#373632'
    - '#f4f5f5'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
